### ISSUE TITLE
Conan issue: unable to find settings.yml during conan config install

### ISSUE THREAD

**Issue by jmcmon** [Twon/Morpheus#196] opened 2023-09-20 09:09 UTC
I’ve had problems trying to get Conan working and after a few attempts, I’m not sure where I’m going wrong.

My environment:
2018 MacBook Pro with Intel Core i9
MacOS Ventura 13.5.2
Python 3.9.6
Apple clang 15.0.0
Pip 23.2.1
cmake  3.27.5
Cmd line shell: bash

I have not used Conan prior to this.

Steps:
1. clone the morpheus repo
2. As per the readme:

```
cd <project root>
python3 -m venv .venv         # Create a Python virtual env
source ./.venv/bin/activate   # Activate the virtual env for bash by source.
pip install conan             # Install latest conan (conan=>2.0)
conan config install ./       # Install supported build profiles

```
This is where I run into problems:
Th first one concerns settings.yml.
Below is a snippet from the Conan config install at the point the error occurs:

```
…
Copying file README.md to /Users/john/CLionProjects/Morpheus/.conan2/.conan2
Copying file .gitignore to /Users/john/CLionProjects/Morpheus/.conan2/.conan2
Copying file .clang-format to /Users/john/CLionProjects/Morpheus/.conan2/.conan2
Copying file global.conf to /Users/john/CLionProjects/Morpheus/.conan2/.conan2
Copying file version.txt to /Users/john/CLionProjects/Morpheus/.conan2/.conan2
Installing settings.yml
ERROR: Failed conan config install: [Errno 2] No such file or directory: '/Users/john/CLionProjects/Morpheus/.conan2/settings.yml'
(.venv) bash-3.2$ 

```

If I run ‘conan install’ from the project root, this inserts a settings.yml into the .conan2. directory

Running ‘conan config install ./’ again gives the same error.

**Comment by jakeheke75** [comment] 2023-09-20 15:02
I am having the same issue as well. Looks like is a recursion problem in the Conan install procedure.
In the Morpheus project directory we have the file `.conanrc` which is changing the default path of the Conan home directory to keep it in the project folder `./.conan2`.
If we try to change the Conan home directory to say `conan_home= ~/.conan2_morpheus` then the command `conan config install ./` doesn't return any error.
Once eliminated this error we can run the subsequent command `conan install ./ -pr:h .conan/profiles/gcc/12/x64-libstdc++11-debug -pr:b .conan/profiles/gcc/12/x64-libstdc++11-debug --build missing` which is now returning a new error:
`ERROR: Error reading '.conan/profiles/gcc/12/x64-libstdc++11-debug' profile: Profile not found: ../../default`
this is because in project directory `Morpheus/.conan/profiles` the `default` file is not available.
@Twon are we missing some important piece of configuration and doing something wrong?
Thanks.

**Comment by Twon** [comment] 2023-09-20 15:43
Hi chaps,

Thanks, both for reporting this, I believe it's an error in the build instruction as the line `conan config install ./`.  This should have been `conan config install ./.conan` which instructs conan to install the profiles in the `/.conan` folder into the local "./.conan2` directory. 

It was obvious there was an error when I looked at Johns output because of the double `.conan2` in the resulting paths for copies files (i.e. `Copying file README.md to /Users/john/CLionProjects/Morpheus/.conan2/.conan2`).  Also it was incorrectly copying files from the root of the project (such as .clang-format, .gitignore, etc).  When I followed the steps on a clean repository I was able to reproduce the errors.  I've raised a fix in this PR: https://github.com/Twon/Morpheus/pull/197

Would you mind trying the instructions with this step corrected (you should remove any existing `.conan2` folder before trying this again though.  

Assuming this fixes it what can I change or improve to make this less confusing for someone experiencing errors next time?  Would it be useful for an explanation of what these steps are for and what they do somewhere?

**Comment by jakeheke75** [comment] 2023-09-20 16:03
Hi Antony, now it works thanks! I tried the next standard build command: `conan install ./ -pr:h .conan/profiles/gcc/12/x64-libstdc++11-debug -pr:b .conan/profiles/gcc/12/x64-libstdc++11-debug --build missing` and I am getting the following error:
`ERROR: Error reading '.conan/profiles/gcc/12/x64-libstdc++11-debug' profile: Profile not found: ../../default`
Effectively if I step into file `x64-libstdc++11-debug`I see that the first row of the file says 
`include(../../default)` and in directory `.conan/profiles` there is no file named `default`...

**Comment by Twon** [comment] 2023-09-20 17:50
Ah right, yes there is a missing call to `conan profile detect --force` here which is the command required to generate a default config (this is the config with settings populated be those Conan is able to discover manually).  The pre-defined profiles which are installed from `./.conan/profiles/` are then all based on overriding the settings specific to the end profile selected.

A couple of command that might be useful here are `conan profile list` which shows the installed profiles:
```
06:36:53 (conan-2-py-3.10.4) antony@Antony Morpheus ±|further_serialisation ✗|→ conan profile list
Migration: Successfully updated settings.yml
Profiles found in the cache:
arch/x64
arch/x86
clang/15/compiler
clang/15/x64-libc++-debug
clang/15/x64-libc++-msr
clang/15/x64-libc++-release
clang/15/x64-libc++-rwdi
compiler/apple-clang
compiler/clang
compiler/gcc
compiler/msvc
config/debug
config/min-size-rel
config/rel-with-deb-info
config/release
cpp/20
cpp/23
default
gcc/12/compiler
gcc/12/x64-libstdc++11-debug
gcc/12/x64-libstdc++11-msr
gcc/12/x64-libstdc++11-release
gcc/12/x64-libstdc++11-rwdi
msvc/193/compiler
msvc/193/x64-debug
msvc/193/x64-msr
msvc/193/x64-release
msvc/193/x64-rwdi
os/current
stl/libc++
stl/libstdc++11
```

Or to see the resulting setting of a profile then to use`conan profile show -pr:b=<profile>`, for example:
```
06:38:19 (conan-2-py-3.10.4) antony@Antony Morpheus ±|further_serialisation ✗|→ conan profile show -pr:b=clang/15/x64-libc++-debug
Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
[conf]
tools.env.virtualenv:powershell=False

Build profile:
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=15
os=Linux
[conf]
tools.env.virtualenv:powershell=False
[buildenv]
CC=/usr/lib/llvm-15/bin/clang
CXX=/usr/lib/llvm-15/bin/clang++
```

This omission is an error on my part, in part because once you run this once you generally do not need to run it again so this will have worked for me with the setting described in the readme when I tested).  I've created a change that adds this step: https://github.com/Twon/Morpheus/pull/198.  Note is not strictly necessary if you intend to use the "conan-default, conan-debug, conan-release" profiles, its only needed for the installed profiles as they all build on default.  But it won't hurt to run this step unnecessarily.  Note this is what we do on the CI, we generate the default profile and then change the settings in there to the ones we want (not the steps on the CI can always be referred to as a source of truth if you run into problems): https://github.com/Twon/Morpheus/blob/04e6235ab5f3acfc9d7e449b28d3488d2192ad2c/.github/workflows/cmake.yml#L136

**Comment by jmcmon** [comment] 2023-09-20 19:25
Thanks for the extra detail folks.
I decided to update everything and ran the updated instructions as per the readme:

```
(.venv) Johns-MacBook-Pro-2:Morpheus john$ conan profile detect --force
detect_api: Found apple-clang 15.0
detect_api: apple-clang>=13, using the major as version

Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu98
compiler.libcxx=libc++
compiler.version=15
os=Macos

WARN: This profile is a guess of your environment, please check it.
WARN: Defaulted to cppstd='gnu17' for apple-clang.
WARN: The output of this command is not guaranteed to be stable and can change in future Conan versions.
WARN: Use your own profile files for stability.
Saving detected profile to /Users/john/CLionProjects/Morpheus/.conan2/profiles/default
(.venv) Johns-MacBook-Pro-2:Morpheus john$ conan config install ./.conan
Copying file x64-libc++-release to /Users/john/CLionProjects/Morpheus/.conan2/profiles/clang/15
Copying file x64-libc++-msr to /Users/john/CLionProjects/Morpheus/.conan2/profiles/clang/15
Copying file x64-libc++-debug to /Users/john/CLionProjects/Morpheus/.conan2/profiles/clang/15
Copying file x64-libc++-rwdi to /Users/john/CLionProjects/Morpheus/.conan2/profiles/clang/15
Copying file compiler to /Users/john/CLionProjects/Morpheus/.conan2/profiles/clang/15
Copying file x64-rwdi to /Users/john/CLionProjects/Morpheus/.conan2/profiles/msvc/193
Copying file x64-msr to /Users/john/CLionProjects/Morpheus/.conan2/profiles/msvc/193
Copying file x64-release to /Users/john/CLionProjects/Morpheus/.conan2/profiles/msvc/193
Copying file x64-debug to /Users/john/CLionProjects/Morpheus/.conan2/profiles/msvc/193
Copying file compiler to /Users/john/CLionProjects/Morpheus/.conan2/profiles/msvc/193
Copying file min-size-rel to /Users/john/CLionProjects/Morpheus/.conan2/profiles/config
Copying file release to /Users/john/CLionProjects/Morpheus/.conan2/profiles/config
Copying file rel-with-deb-info to /Users/john/CLionProjects/Morpheus/.conan2/profiles/config
Copying file debug to /Users/john/CLionProjects/Morpheus/.conan2/profiles/config
Copying file x64-libstdc++11-release to /Users/john/CLionProjects/Morpheus/.conan2/profiles/gcc/12
Copying file x64-libstdc++11-rwdi to /Users/john/CLionProjects/Morpheus/.conan2/profiles/gcc/12
Copying file x64-libstdc++11-msr to /Users/john/CLionProjects/Morpheus/.conan2/profiles/gcc/12
Copying file x64-libstdc++11-debug to /Users/john/CLionProjects/Morpheus/.conan2/profiles/gcc/12
Copying file compiler to /Users/john/CLionProjects/Morpheus/.conan2/profiles/gcc/12
Copying file libc++ to /Users/john/CLionProjects/Morpheus/.conan2/profiles/stl
Copying file libstdc++11 to /Users/john/CLionProjects/Morpheus/.conan2/profiles/stl
Copying file 23 to /Users/john/CLionProjects/Morpheus/.conan2/profiles/cpp
Copying file x64 to /Users/john/CLionProjects/Morpheus/.conan2/profiles/arch
Copying file x86 to /Users/john/CLionProjects/Morpheus/.conan2/profiles/arch
Copying file current to /Users/john/CLionProjects/Morpheus/.conan2/profiles/os
Copying file clang to /Users/john/CLionProjects/Morpheus/.conan2/profiles/compiler
Copying file msvc to /Users/john/CLionProjects/Morpheus/.conan2/profiles/compiler
Copying file apple-clang to /Users/john/CLionProjects/Morpheus/.conan2/profiles/compiler
Copying file gcc to /Users/john/CLionProjects/Morpheus/.conan2/profiles/compiler

```
So far, so good.
I then updated the compiler.libcxx line in my .conan2/profiles/default file 

```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu98
**compiler.libcxx=libstdc++11**
compiler.version=15
os=Macos
```

I'm guessing the compiler.cppstd=gnu98 line needs editing also?

Further commands yielded the following:

```
(.venv) Johns-MacBook-Pro-2:Morpheus john$ conan profile list
Profiles found in the cache:
arch/x64
arch/x86
clang/15/compiler
clang/15/x64-libc++-debug
clang/15/x64-libc++-msr
clang/15/x64-libc++-release
clang/15/x64-libc++-rwdi
compiler/apple-clang
compiler/clang
compiler/gcc
compiler/msvc
config/debug
config/min-size-rel
config/rel-with-deb-info
config/release
cpp/23
default
gcc/12/compiler
gcc/12/x64-libstdc++11-debug
gcc/12/x64-libstdc++11-msr
gcc/12/x64-libstdc++11-release
gcc/12/x64-libstdc++11-rwdi
msvc/193/compiler
msvc/193/x64-debug
msvc/193/x64-msr
msvc/193/x64-release
msvc/193/x64-rwdi
os/current
stl/libc++
stl/libstdc++11
(.venv) Johns-MacBook-Pro-2:Morpheus john$ conan profile show -pr:b=clang/15/x64-libc++-debug
ERROR: Invalid setting 'libstdc++11' is not a valid 'settings.compiler.libcxx' value.
Possible values are ['libstdc++', 'libc++']
Read "http://docs.conan.io/2/knowledge/faq.html#error-invalid-setting"

```

Wondering if I've made an unnecessary edit in my [settings]?
Thanks

**Comment by jakeheke75** [comment] 2023-09-20 19:41
Hi Antony, first of all thanks for the patience and for taking the time to explain the behaviour and the functionalities of Conan.
So, as you suggested I executed the command `conan profile detect --force`. Since we recently migrated to Conan 2.0 the `default` profile has been created under directory `./.conan2/profiles` and not under directory `./.conan/profiles` as it used to happen before with Conan 1.x.
Then I tried to run again the command `conan install ./ -pr:h .conan/profiles/gcc/12/x64-libstdc++11-debug -pr:b .conan/profiles/gcc/12/x64-libstdc++11-debug --build missing` and I am getting the following error:
`ERROR: Error reading '.conan/profiles/gcc/12/x64-libstdc++11-debug' profile: Profile not found: ../../default`
I guess because we should look for the `default` Conan 2 profile file under the directory `../../../../.conan2/profiles/default`.
Therefore if you think that this is the correct approach to solve this issue I can prepare a PR and update all the profiles under the directories:
```
./conan/profiles/clang
./conan/profiles/gcc
./conan/profiles/msvc
```
with the instruction `include(../../../../.conan2/profiles/default)`.
Thanks.
Cheers,
Gianmario

**Comment by jmcmon** [comment] 2023-09-20 19:47
Hi Gianmario, Antony,
I took a not dissimilar approach just now and the project is building for me.
I ran  `conan profile detect --force` and then copied the default profile from .conan2 to .conan
That was enough for the `conan install...` command to work and the project has been building for the last few minutes.
I've seen a few warnings, but no errors yet. Will see what the result is and if I need to change my compiler.libcxx setting.

Thanks,
John

**Comment by jakeheke75** [comment] 2023-09-20 19:52
> ```
> [settings]
> arch=x86_64
> build_type=Release
> compiler=apple-clang
> compiler.cppstd=gnu98
> **compiler.libcxx=libstdc++11**
> compiler.version=15
> os=Macos
> ```
> Wondering if I've made an unnecessary edit in my [settings]? Thanks

Hi John,
I think that you can avoid editing your own Conan profile since the project is proving under directory `Morpheus/.conan/profiles` already all the profiles for all supported configurations.
With that said I think that you can easily solve the error by removing the beginning and ending star characters. Just  `compiler.libcxx=libstdc++11` instead of `**compiler.libcxx=libstdc++11**`.
Cheers,
Gianmario

**Comment by jmcmon** [comment] 2023-09-20 20:05
Thanks Gianmario for the details - it's all appreciated as this is my first time using conan and it's something I've been meaning to try for a long time.
For what it's worth, the extra asterisks are some formatting on this website as I wanted to show that line in bold, but this is what happened !

**Comment by jakeheke75** [comment] 2023-09-20 20:25
> Thanks Gianmario for the details - it's all appreciated as this is my first time using conan and it's something I've been meaning to try for a long time. For what it's worth, the extra asterisks are some formatting on this website as I wanted to show that line in bold, but this is what happened !

Ahhh ok... By the way the error that you are getting:
```
ERROR: Invalid setting 'libstdc++11' is not a valid 'settings.compiler.libcxx' value.
Possible values are ['libstdc++', 'libc++']
```
it's because for compiler `apple-clang` the value `libstdc++11` is not a valid `settings.compiler.libcxx` value.
You can check the possible list of values in the file `/Morpheus/.conan2/settings.yml` under the section `compiler` for `apple-clang`. The possible values are `libcxx: [libstdc++, libc++]`.
Cheers,
Gianmario

**Comment by Twon** [comment] 2023-09-20 21:21
Perhaps at this point, I should provide a bit more context for the way things are set up now. I've made some choices in the current setup to support Conan 2. However, previously I was using Conan 1 and things were simpler. Conan 1 supported commands to generate a config (`conan config init` and then update values in the profile `conan profile update settings.compiler.cppstd=20 default`):https://github.com/Twon/Morpheus/blob/5c2c92521f2e66fe25ae6c3d06d1dd1837cf3a8e/.github/workflows/cmake.yml#L111

For the release of Conan 2, they have decided to remove these commands. You can still generate a default profile by `conan profile detect --force` but there is no mechanism to update values in it.  For the CI I have used bash commands to update these values via the sed command: https://github.com/Twon/Morpheus/blob/31ec0232904b0b14b89ec7b43c260bbd08f1925d/.github/workflows/cmake.yml#L137 

However, they did introduce profiles: https://docs.conan.io/2.0/reference/config_files/profiles.html.  This is the system of files which override and provide programmatic ways to overload value (see https://github.com/Twon/Morpheus/blob/31ec0232904b0b14b89ec7b43c260bbd08f1925d/.conan/profiles/os/current#L2 for an example here).  I relied heavily on this video while migrating to Conan 2: https://www.youtube.com/watch?v=NliYPQBqNZY.  I'm not sure there is a general best practice available for this yet, but setting up the profiles in the way that I have so there is a profile for all of the support configurations seemed logical.  There may be a better way to do this but it seemed a reasonable starting point. That said I am still learning so if we can find a better way happy to look at alternatives.

**Comment by jakeheke75** [comment] 2023-09-21 19:32
> I relied heavily on this video while migrating to Conan 2: https://www.youtube.com/watch?v=NliYPQBqNZY. I'm not sure there is a general best practice available for this yet, but setting up the profiles in the way that I have so there is a profile for all of the support configurations seemed logical. There may be a better way to do this but it seemed a reasonable starting point. That said I am still learning so if we can find a better way happy to look at alternatives.

Thanks Antony for explaining the whole logic :pray:
In my humble opinion the logic of the approach is absolutely good. Since this specific Conan build issue has been solved I am going to close it.
Cheers,
Gianmario

**Closed by jakeheke75** 2023-09-21 19:32 UTC
Labels: issue

**Comment by Twon** [comment] 2023-09-22 09:15
Thank you both for wresting with the build instructions and helping me to iron out issues out here. Much appreciated!
